name: Test

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: windows-2019

    steps:  
      - name: test
        shell: bash
        run: |-
          C:\ProgramData\Chocolatey\bin\vswhere.exe -products * -requires Microsoft.Component.MSBuild -property installationPath -latest
          which msbuild
