name: Test

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: windows-2019

    steps:
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
  
      - name: test
        shell: bash
        run: |-
          which msbuild
